apiVersion: apps/v1
kind: Deployment
metadata:
  name: hrm-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hrm-backend
  template:
    metadata:
      labels:
        app: hrm-backend
    spec:
      containers:
      - name: hrm-backend
        image: jaayshaun/lab3-backend:latest
        ports:
        - containerPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hrm-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hrm-frontend
  template:
    metadata:
      labels:
        app: hrm-frontend
    spec:
      containers:
      - name: hrm-frontend
        image: jaayshaun/lab3-frontend:latest
        ports:
        - containerPort: 3000

