# service-backend.yaml
apiVersion: v1
kind: Service
metadata:
  name: hrm-backend
spec:
  selector:
    app: hrm-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

